# Introduction

In this notebook we'll learn how to use NumPy to work with numerical data. 

<img src="https://i.imgur.com/dZ1XE9o.png" width=400>

# Import Statements

In [ ]:
import numpy as np

import matplotlib.pyplot as plt # A library for plotting reading images

# Understanding NumPy's ndarray

NumPy's most amazing feature is the **powerful** ndarray.

<img src="https://miro.medium.com/max/1400/1*X0Dg7QfSYtWhSAu-afi8-g.png" width=500>

#### 1-Dimensional Arrays (Vectors)

In [ ]:
# Create new ndarray from scatch
my_array = np.array([1.1, 9.2, 8.1, 4.7])

In [ ]:
# Show rows and columns
my_array.shape

(4,)

In [ ]:
# Accessing elements by index
my_array[2]

8.1

In [ ]:
# Show dimensions of an array
my_array.ndim

1

#### 2-Dimensional Arrays (Matrices)

In [ ]:
array_2d = np.array([[1, 2, 3, 9], 
                     [5, 6, 7, 8]])

print(f'array_2d has {array_2d.ndim} dimensions')
print(f'Its shape is {array_2d.shape}')
print(f'It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns')
print(array_2d)

array_2d has 2 dimensions
Its shape is (2, 4)
It has 2 rows and 4 columns
[[1 2 3 9]
 [5 6 7 8]]


In [ ]:
# Access the 3rd value in the 2nd row
array_2d[1,2]

7

In [ ]:
# Access all the values in the first row
array_2d[0, :]

array([1, 2, 3, 9])

#### N-Dimensional Arrays (Tensors)

**Challenge**: 
* How many dimensions does the array below have? 
* What is its shape (i.e., how many elements are along each axis)?
* Try to access the value `18` in the last line of code.
* Try to retrieve a 1 dimensional vector with the values `[97, 0, 27, 18]`
* Try to retrieve a (3,2) matrix with the values `[[ 0,  4], [ 7,  5], [ 5, 97]]`

*Hint*: You can use the `:` operator just as with Python Lists.

In [ ]:
mystery_array = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                        
                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],
                          
                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])

# Note all the square brackets!

In [ ]:
print(f'We have {mystery_array.ndim} dimensions')
print(f'The shape is {mystery_array.shape}')

We have 3 dimensions
The shape is (3, 2, 4)


In [ ]:
# Axis 0: 3rd element. Axis 1: 2nd Element. Axis 3: 4th Element
mystery_array[2, 1, 3]

18

In [ ]:
# Retrieve all the elements on the 3rd axis that are at
# position 2 on the first axis and position 1 on the second axis.
mystery_array[2, 1, :]

array([97,  0, 27, 18])

In [ ]:
# All the first elements on axis number 3
mystery_array[:, :, 0]

array([[ 0,  4],
       [ 7,  5],
       [ 5, 97]])

# NumPy Mini-Challenges

#### **Challenge 1**: Use [`.arange()`](https://numpy.org/devdocs/reference/generated/numpy.arange.html)to createa a vector `a` with values ranging from 10 to 29. You should get this:

`print(a)`

`[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]`

#### **Challenge 2**: Use Python slicing techniques on `a` to:
* Create an array containing only the last 3 values of `a`
* Create a subset with only the 4th, 5th, and 6th values
* Create a subset of `a` containing all the values except for the first 12 (i.e., `[22, 23, 24, 25, 26, 27, 28, 29]`)
* Create a subset that only contains the even numbers (i.e, every second number)

Remember the list we have studied a[start:stop:step]

#### **Challenge 3**:Reverse the order of the values in `a`, so that the first element comes last:

`[29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10]`


#### **Challenge 4**: Print out all the indices of the non-zero elements in this array: [6,0,9,0,0,5,0]

#### **Challenge 5**: Use NumPy to generate a 3x3x3 array with random numbers

Hint: Use the [`.random()` function](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

#### **Challenge 6**: Use [`.linspace()`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) to create a vector `x` of size 9 with values spaced out evenly between 0 to 100 (both included).

#### **Challenge 8**: Use NumPy to generate an array called `noise` with shape 128x128x3 that has random values. Then use Matplotlib's [`.imshow()`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) to display the array as an image. 

# Linear Algebra with Vectors

In [ ]:
v1 = np.array([4, 5, 2, 7])
v2 = np.array([2, 1, 3, 3])

In [ ]:
v1+v2

array([ 6,  6,  5, 10])

In [ ]:
# Python Lists vs ndarrays
list1 = [4, 5, 2, 7]
list2 = [2, 1, 3, 3]
list1 + list2

[4, 5, 2, 7, 2, 1, 3, 3]

In [ ]:
v1 * v2

array([ 8,  5,  6, 21])

# Broadcasting and Scalars


In [ ]:
array_2d = np.array([[1, 2, 3, 4], 
                     [5, 6, 7, 8]])
print(f'Dimensions: {array_2d.ndim}')
print(f'Shape: {array_2d.shape}')

Dimensions: 2
Shape: (2, 4)


In [ ]:
array_2d + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [ ]:
array_2d * 5

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40]])

# Matrix Multiplication with @ and .matmul()

<img src=https://i.imgur.com/LCdhmi8.png width=350>

In [ ]:
a1 = np.array([[1, 3],
               [0, 1],
               [6, 2],
               [9, 7]])

b1 = np.array([[4, 1, 3],
               [5, 8, 5]])

print(f'{a1.shape}: a has {a1.shape[0]} rows and {a1.shape[1]} columns.')
print(f'{b1.shape}: b has {b1.shape[0]} rows and {b1.shape[1]} columns.')
print('Dimensions of result: (4x2)*(2x3)=(4x3)')

(4, 2): a has 4 rows and 2 columns.
(2, 3): b has 2 rows and 3 columns.
Dimensions of result: (4x2)*(2x3)=(4x3)


**Challenge**: Let's multiply `a1` with `b1`. Looking at the wikipedia example above, work out the values for c12 and c33 on paper. Then use the [`.matmul()`](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html) function or the `@` operator to check your work. 

# Reshaping Matrix with [.reshape()](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [ ]:
a1 = np.array([[1, 3],
               [0, 1],
               [6, 2],
               [9, 7]])